services:
  gateway:
    networks: 
      - vas
    build: .
    restart: always
    environment:
      DATA_URL: ${DATA_URL}
      DATA_API_KEY: ${DATA_API_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      MAPS_API_KEY: ${MAPS_API_KEY}
    ports:
      - 8080:8080

networks:
  vas:
    name: vikeandsell
    external: true