services:
  gateway:
    networks: 
      - vas
    build:
      context: .
      dockerfile: flask/Dockerfile-https
    restart: always
    environment:
      DATA_URL: ${DATA_URL}
      DATA_API_KEY: ${DATA_API_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      MAPS_API_KEY: ${MAPS_API_KEY}
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    ports:
      - 443:443

networks:
  vas:
    name: vikeandsell
    external: true
