
services:
  test:
    build:
      context: .
      dockerfile: tests/Dockerfile
    restart: no
    environment:
      DATA_URL: test
      DATA_API_KEY: testapikey
      JWT_SECRET_KEY: testjwtsecret
