
services:
  test:
    build:
      context: .
      dockerfile: tests/Dockerfile
    environment:
      DATA_URL: http://test
      DATA_API_KEY: testapikey
      JWT_SECRET_KEY: testjwtsecret
      MAPS_API_KEY: testmapsapikey
      SEARCH_REC_URL: ${SEARCH_REC_URL}
